[package]
name = "game"
version = "0.1.0"
edition = "2021"
authors = ["st0rmbtw"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.8.0", default-features = false, features = ["bevy_sprite", "bevy_text", "bevy_ui", "bevy_render", "bevy_core_pipeline", "bevy_winit", "png", "filesystem_watcher"] }
bevy_asset_loader = { version = "0.12.1", features = ["2d", "stageless"] }
lazy_static = "1.4.0"
rand = "0.8.5"
interpolation = "0.2"
ndarray = "0.15.6"
noise = "0.8.1"
iyes_loopless = "0.7.1"
autodefault = "2.0.0"
bevy_hanabi = { git = "https://github.com/djeedai/bevy_hanabi.git", branch = "main", default-features = false, features = ["2d"] }
bevy-inspector-egui = "0.13.0"
bevy_prototype_debug_lines = { version = "0.8", optional = true }
bevy_ecs_tilemap = { version = "0.8.0" }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[features]
debug = ["dep:bevy_prototype_debug_lines"]
debug_grid = ["dep:bevy_prototype_debug_lines"]
debug_movement = []
free_camera = []