[package]
name = "game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.7.0" }
bevy_rapier2d = "0.15.0"

[profile.dev.package.bevy_rapier2d]
opt-level = 3