[package]
name = "game"
version = "0.1.0"
edition = "2021"
authors = ["st0rmbtw"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.8.0", default-features = false, features = ["bevy_sprite", "bevy_text", "bevy_ui", "bevy_render", "bevy_core_pipeline", "bevy_winit", "dynamic", "png", "filesystem_watcher"] }
bevy-inspector-egui = "0.12.1"
bevy_asset_loader = { version = "0.12.1", features = ["2d", "stageless"] }
bevy_rapier2d = { version = "0.16.2", features = ["debug-render"] }
lazy_static = "1.4.0"
rand = "0.8.5"
smallvec = "1.9.0"
interpolation = "0.2"
ndarray = "0.15.6"
noise = "0.7.0"
iyes_loopless = "0.7.1"
autodefault = "2.0.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
