[package]
name = "game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.8.0" }
bevy-inspector-egui = "0.12.0"
bevy_asset_loader = { version = "0.12.0", features = ["2d"] }
bevy_rapier2d = { version = "0.16.0", features = ["debug-render"] }
lazy_static = "1.4.0"
rand = "0.8.5"
smallvec = "1.9.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
