[package]
name = "game"
version = "0.1.0"
edition = "2021"
authors = ["st0rmbtw"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.9.1" }
bevy_asset_loader = { version = "0.14.1", features = ["2d", "stageless"] }
lazy_static = "1.4.0"
rand = "0.8.5"
interpolation = "0.2.0"
ndarray = "0.15.6"
noise = "0.8.2"
iyes_loopless = "0.9.1"
autodefault = "2.0.0"
bevy_hanabi = { version = "0.5.3", default-features = false, features = ["2d"] }
bevy-inspector-egui = "0.17.0"
bevy_prototype_debug_lines = { version = "0.9.0", optional = true }
bevy_ecs_tilemap = { version = "0.9.0" }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.88"

[profile.dev]
opt-level = 0
incremental=true
lto = false

[profile.release]
opt-level = 3
incremental=true
lto = true

[profile.dev.package."*"]
opt-level = 3

[features]
debug = ["dep:bevy_prototype_debug_lines"]
debug_grid = ["dep:bevy_prototype_debug_lines"]
debug_movement = []
free_camera = []